import React, { useEffect } from 'react';

export default function HowItWorksModal({ isOpen, onClose }) {
  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape') onClose();
    };
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      document.addEventListener('keydown', handleEscape);
    }
    return () => {
      document.body.style.overflow = '';
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal__header">
          <h2 className="modal__title">How DeepScan Works</h2>
          <button
            type="button"
            className="modal__close"
            onClick={onClose}
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="modal__body">
          <p className="modal__intro">
            DeepScan analyzes images to detect whether they were likely generated by AI.
            Here’s how to use it and what the results mean.
          </p>

          <section className="modal__section">
            <h3>Step 1: Upload an image</h3>
            <p>
              Drag and drop an image or click to browse. Supported formats: JPEG, PNG, and WEBP (max 5MB).
            </p>
          </section>

          <section className="modal__section">
            <h3>Step 2: Analyze</h3>
            <p>
              Click <strong>Analyze Image</strong>. DeepScan sends your image to our backend, which inspects it
              for AI-generated patterns, artifacts, and metadata.
            </p>
          </section>

          <section className="modal__section">
            <h3>Step 3: Review results</h3>
            <p>You’ll see:</p>
            <ul>
              <li><strong>Verdict</strong> — Likely AI-Generated, Uncertain, or Likely Authentic</li>
              <li><strong>AI Probability</strong> — Overall score (0–100%). Higher = more likely AI-generated</li>
              <li><strong>Score breakdown</strong> — Model score, artifact score, and metadata score</li>
              <li><strong>EXIF details</strong> — Camera info and timestamp if present; missing values may suggest AI generation</li>
            </ul>
          </section>

          <section className="modal__section">
            <h3>What we check</h3>
            <ul>
              <li><strong>Model analysis</strong> — Patterns typical of AI image models</li>
              <li><strong>Artifact detection</strong> — Texture inconsistencies, unusual edges, or visual artifacts</li>
              <li><strong>Metadata</strong> — EXIF data; AI images often lack camera make, model, or timestamps</li>
            </ul>
          </section>

          <div className="modal__footer">
            <button
              type="button"
              className="modal__cta"
              onClick={() => {
                onClose();
                document.getElementById('analyzer')?.scrollIntoView({ behavior: 'smooth' });
              }}
            >
              Try it now
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
