import React from 'react';
import { Link } from 'react-router-dom';

export default function AboutPage() {
  return (
    <div className="page">
      <div className="page__content">
        <h1 className="page__title">About DeepScan</h1>
        <p className="page__intro">
          DeepScan is an AI image authenticity detector built to help users verify whether images were generated by AI tools.
        </p>

        <section className="page__section">
          <h2>Our mission</h2>
          <p>
            As AI-generated imagery becomes more common, distinguishing real from synthetic content is increasingly important. DeepScan aims to provide a simple, accessible tool for image authenticity checks.
          </p>
        </section>

        <section className="page__section">
          <h2>How it works</h2>
          <p>
            We analyze images using model-based detection, artifact inspection, and EXIF metadata. The system combines these signals to produce an overall AI probability score.
          </p>
        </section>

        <section className="page__section">
          <h2>Privacy</h2>
          <p>
            Images are sent to our backend for analysis. We do not store or share your uploads beyond what's needed to return results.
          </p>
        </section>

        <section className="page__section">
          <h2>Technology</h2>
          <p>
            Built with React, Express, and modern web technologies. Designed for ease of use and clear, actionable results.
          </p>
        </section>

        <div className="page__actions">
          <Link to="/" className="page__btn page__btn--primary">
            Try DeepScan
          </Link>
        </div>
      </div>
    </div>
  );
}
