import React from 'react';
import { Link } from 'react-router-dom';

export default function HowItWorksPage() {
  return (
    <div className="page">
      <div className="page__content">
        <h1 className="page__title">How DeepScan Works</h1>
        <p className="page__intro">
          DeepScan analyzes images to detect whether they were likely generated by AI.
          Here's how to use it and what the results mean.
        </p>

        <section className="page__section">
          <h2>Step 1: Upload an image</h2>
          <p>
            Drag and drop an image or click to browse. Supported formats: JPEG, PNG, and WEBP (max 5MB).
          </p>
        </section>

        <section className="page__section">
          <h2>Step 2: Analyze</h2>
          <p>
            Click <strong>Analyze Image</strong>. DeepScan sends your image to our backend, which inspects it
            for AI-generated patterns, artifacts, and metadata.
          </p>
        </section>

        <section className="page__section">
          <h2>Step 3: Review results</h2>
          <p>You'll see:</p>
          <ul>
            <li><strong>Verdict</strong> — Likely AI-Generated, Uncertain, or Likely Authentic</li>
            <li><strong>AI Probability</strong> — Overall score (0–100%). Higher = more likely AI-generated</li>
            <li><strong>Score breakdown</strong> — Model score, artifact score, and metadata score</li>
            <li><strong>EXIF details</strong> — Camera info and timestamp if present; missing values may suggest AI generation</li>
          </ul>
        </section>

        <section className="page__section">
          <h2>What we check</h2>
          <ul>
            <li><strong>Model analysis</strong> — Patterns typical of AI image models</li>
            <li><strong>Artifact detection</strong> — Texture inconsistencies, unusual edges, or visual artifacts</li>
            <li><strong>Metadata</strong> — EXIF data; AI images often lack camera make, model, or timestamps</li>
          </ul>
        </section>

        <div className="page__actions">
          <Link to="/" className="page__btn page__btn--primary">
            Try it now
          </Link>
        </div>
      </div>
    </div>
  );
}
